---
format:
  html:
    self-contained: true
    theme: scss/theme-index.scss
---

```{r}
library(htmlwidgets)
library(dplyr)
library(here)
library(readr)
library(tibble)
library(igraph)
library(networkD3)

# load(here("data/pub_graph.RData"))
pub_graph <- read_rds(here("data/pub_graph.rds"))
pub_meta <- read_rds(here("data/pub_meta.rds"))
```

```{r}
nodes <- pub_graph |>
  as_data_frame("vertices") |>
  mutate(id = row_number() - 1) |>
  remove_rownames() |>
  left_join(pub_meta)

node_ids <- nodes |> select(name, id)
links <- pub_graph |>
  as_data_frame("edges") |>
  left_join(node_ids, by = c("from" = "name")) |>
  left_join(node_ids, by = c("to" = "name")) |>
  rename(source = id.x, target = id.y)

nodeClick = 'window.open("https://oecs.mit.edu/pub/" + d.nodesize, "_blank");'

forceNetwork(
  Links = links, Nodes = nodes, Source = "source",
  Target = "target", NodeID = "name",
  Value = "similarity_renorm",
  Nodesize = "slug", # hack to make slug available
  Group = "group",
  linkWidth = JS("function(d) { return d.slug; }"),
  radiusCalculation = JS("6"),
  charge = -100,
  zoom = FALSE, bounded = TRUE,
  colourScale = JS("d3.scaleOrdinal(d3.schemeCategory10);"),
  opacity = 1, opacityNoHover = TRUE,
  fontFamily = "Noto Sans", fontSize = 12,
  height = 1500, width = 1200,
  clickAction = nodeClick)
```
